language: python

os:
  - linux

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  include:
    - os: osx
      osx_image: xcode11
      language: shell

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew unlink pyenv;
      brew install pyenv;
      pyenv install $TRAVIS_PYTHON_VERSION;
      pyenv global $TRAVIS_PYTHON_VERSION;
      pip install --upgrade pip;
    fi

install:
  - virtualenv /tmp/test-env
  - /tmp/test-env/bin/python -VV
  - /tmp/test-env/bin/pip install codecov coverage
  - /tmp/test-env/bin/python setup.py install

script:
  - /tmp/test-env/bin/python setup.py test

after_success:
  - codecov 

