language: python

os:
  - linux
  - osx

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "2.7"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - virtualenv /tmp/test-env
  - /tmp/test-env/bin/python -VV
  - /tmp/test-env/bin/pip install codecov coverage
  - /tmp/test-env/bin/python setup.py install

script:
  - /tmp/test-env/bin/python setup.py test

after_success:
  - codecov 

