language: python

os:
  - linux

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  include:
    - os: osx
      language: generic
      before_install:
        brew update;
        brew install python3;
        pip3 install --upgrade pip;
        pip3 install virtualenv;

install:
  - virtualenv /tmp/test-env
  - /tmp/test-env/bin/python -VV
  - /tmp/test-env/bin/pip install codecov coverage
  - /tmp/test-env/bin/python setup.py install

script:
  - /tmp/test-env/bin/python setup.py test

after_success:
  - codecov 

